# Generated by Django 4.0.3 on 2022-03-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfc', '0003_player_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='cauntry',
            new_name='country',
        ),
    ]
